### ISSUE TITLE
Syntax error with python3

### ISSUE THREAD

**Issue by somik123** [rofl0r/nat-tunnel#1]
Hi,

Upon trying to run the script, I got the error:

```
python3 natsrv.py
  File "natsrv.py", line 89
    print _timestamp() + l.rstrip('\n')
                   ^
SyntaxError: invalid syntax
```

**Comment by rofl0r** [comment]
use python2

**Comment by rofl0r** [comment]
i took a quick look and porting to py3 was easy, so i fixed it. should work now (at least no syntax errors)
